name: Consolidator
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install pyinstaller wxpython
    - name: Build app
      run: |
        pyinstaller --onedir --windowed --name "Consolidator" consolidator.py
    - name: Create DMG (optional)
      run: |
        brew install create-dmg
        create-dmg --volname "Consolidator" --window-pos 200 120 --window-size 600 300 --icon-size 100 --icon "Consolidator.app" 175 120 --hide-extension "Consolidator.app" --app-drop-link 425 120 "Consolidator.dmg" "dist/"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Consolidator-macOS
        path: dist/